sudo: false
language: ruby

branches:
  except:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speed up installation of nokogiri

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

install:
- bundle install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
