language: ruby
rvm:
- 2.4.2

branches:
  except:
    - master

install:
- bundle install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
