# general
title: Syntheta.se
markdown: kramdown
description: A personal blog of code snippets and electronics projects
url: https://syntheta.se
author: David Allen
include:
  - _pages

# dev
host: 0.0.0.0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

# syntax highlighting
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# exclude during build
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - Dockerfile
  - docker-compose.yml

sass:
  sass_dir: "assets/stylesheets/_sass"
  style: compressed
  sourcemap: development
