# general
title: Syntheta.se
markdown: kramdown
description: A personal blog of code snippets and electronics projects
url: https://syntheta.se
author: David Allen

# syntax highlighting
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

include: ["_pages"]

# gem plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
