# general
title: Syntheta.se
markdown: kramdown
description: A personal blog of code snippets and electronics projects
url: https://syntheta.se
author: David Allen
include: ["_pages"]

# syntax highlighting
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

jekyll-minifier:
  compress_javascript: false

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-minifier
  - jekyll-paginate-v2

# exclude during build
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
