# general
title: Syntheta.se
markdown: kramdown
description: A personal blog of code snippets and electronics projects
url: https://syntheta.se
author: David Allen
include: ['_pages']

# syntax highlighting
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# gem plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

# exclude during build
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
