# general
name: Syntheta.se
markdown: kramdown
description: A personal blog of code snippets and electronics projects
url: http://syntheta.se

# syntax highlighting
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

include: ["_pages"]

# gems
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
